stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
      - src/data/data_ingestion.py

  extract_features:
    cmd: python src/features/extract_features.py
    deps:
      - src/features/extract_features.py
    params:
      - extract_features.mini_batch_kmeans.n_clusters
      - extract_features.mini_batch_kmeans.n_init
      - extract_features.mini_batch_kmeans.random_state
      - extract_features.ewma.alpha
    outs:
      - models/scaler.joblib
      - models/mini_batch_kmeans.joblib
      - data/processed/features.csv

  feature_processing:
    cmd: python src/features/feature_processing.py
    deps:
      - src/features/feature_processing.py
      - data/processed/features.csv
    outs:
      - data/processed/train.csv
      - data/processed/test.csv  
